### ISSUE TITLE
Update runtime

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.gitg#10]
You're current runtime is GNOME 3.32, which is as of today end-of-life. Could you update it to a more recent version?

**Comment by albfan** [comment]
We will do when we release a new version for gitg. But there's no ETA for that (gitg is not under GNOME release cycle)

**Comment by Eonfge** [comment]
Please reconsider. 3.32 is no longer supported and it will no longer receive security updates. It doesn't have to be right away, but do consider updating to 3.34 or 3.36 this month.

**Comment by albfan** [comment]
It will be done in short, for sure.

**Comment by albfan** [comment]
Next on the list!
