### ISSUE TITLE
org.gnome.Platform//41 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/org.gnome.gitg#22]
The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.

**Comment by albfan** [comment]
We plan to upgrade with next release from gitg

**Comment by bbhtt** [comment]
> We plan to upgrade with next release from gitg

Hello, is there a blocker to using 43 or 44 with the existing release? If there is none, I can open a PR to update it since it is almost 2 versions out of date by now with 45 nearning. Thanks!
