### ISSUE TITLE
App doesn't contain git executable

### ISSUE THREAD

**Issue by wjt** [flathub/org.gnome.gitg#23]
I have a git pre-commit hook that invokes `git`. For the curious: it wants to determine the current branch name, see if it matches Endless's convention for naming the branch after the Phabricator ticket it relates to, and if so add a URL to the message. So it runs `git rev-parse --abbrev-ref HEAD` (though it could also run `git symbolic-ref --short HEAD`).

But `git` is not present in the `PATH` of Gitg, so this hook fails with:

```
git: command not found
```

and as a result I can't commit (or merge).

(I don't want to work around this by reading `.git/HEAD` directly. For starters, that doesn't work in a [git worktree](https://git-scm.com/docs/git-worktree) where `.git` is a text file not a directory.)

**Comment by albfan** [comment]
Yes, gitg do not include git it is based on libgit2. I'm unsure how a sandbox can enable access to external host apps.

I can only think on `run_on_host` from GNOME Builder, which "automagically" find executables on host if they are not included on flatpak. Maybe @chergert can suggest if that is possible somehow

**Comment by chergert** [comment]
Well, there are a couple of options.

The easiest option would be to make `gitg` use `org.gnome.Sdk` instead of `org.gnome.Platform`. Then you'd have `git` for free.

The next easiest option might be to require scripts to have knowledge that it's running under gitg, and wrap the command in `flatpak-spawn`. That requires changes to user-scripts, but could be done by setting an environment variable like `GITG_VERSION=the_version_number` so that scripts can check against it. This requires little code change in gitg, but potentially lots of scripts to be updated (and that may be a non-starter).

You would have to ensure gitg has access to the `--talk-name=org.freedesktop.Flatpak` and `--allow=devel` so you can spawn processes on the host using `flatpak-spawn --host`.

With those enumerated, the best (and possibly hardest option) would be a combination of the second and actually plumbing libgit2/libgit2-glib to do the flatpak-spawn automatically. I don't know how hooks are processed in libgit2, or if you get a callback to manage the subprocess execution, but if you did, you could synthesize a prefix with `flatpak-spawn --host ...` as necessary.

**Comment by wjt** [comment]
Option 4: copy `/usr/bin/git` and `/usr/libexec/git-core` from the SDK to `/app`? Might work!

**Comment by albfan** [comment]
I think use `git` on hooks is so common that use Sdk makes sense. Asking some maintainer like @barthalion if this is or not a good idea.

But in the end, as hooks are setup on host, it can fail all the time if hook is not run on host.

if you hook runs some rest api check and you filter with jq or use python in a hook use Sdk probably will not fix it.

**Comment by wjt** [comment]
Fair point. In this case the hook is wholly self-contained to the repo. But other hooks may run external tools…

**Comment by chergert** [comment]
Can you create `/app/bin/git` which is a shell script to defer to the host?

```sh
$ flatpak run --talk-name=org.freedesktop.Flatpak --allow=devel org.gnome.Platform//master 
[📦 org.gnome.Platform ~]$ flatpak-spawn --host git 
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]

...
```

**Comment by albfan** [comment]
Thanks for explanation @chergert 

Then I thing we need to mimic the is_flatpak from gnome builder. If I'm correct looks like detecting is to test:

      if (g_file_test ("/.flatpak-info", G_FILE_TEST_EXISTS))

https://gitlab.gnome.org/GNOME/gitg/-/blob/master/libgitg/gitg-hook.vala#L201

```
$ pwd
/home/alberto/projects/vala/gitg
$ echo "echo '{\"foo\": \"bar\", \"bazz\": 5}' | jq .foo" > .git/hooks/post-commit 
$ flatpak run --talk-name=org.freedesktop.Flatpak --command=bash --allow=devel org.gnome.gitg
[📦 org.gnome.gitg gitg]$ flatpak-spawn --host /home/alberto/projects/vala/gitg/.git/hooks/post-commit
"bar"
[📦 org.gnome.gitg gitg]$ exit
exit
$ 
```

So this needs changes on gitg. @wjt are you able to work on this? opening an issue on gitg like "running hooks on flatpak runtime" could be a good start

**Comment by chergert** [comment]
You can probably do it without any changes to gitg and only change the Flatpak packaging.

Create a script with something like this, and copy it into `/app/bin/git` in the manifest.

```sh
#!/bin/sh
exec flatpak-spawn --host git "$@"
```

**Comment by wjt** [comment]
Honestly I have very mixed feelings about my report leading to the "arbitrary sandbox escape" sandbox hole being added. (Though, host filesystem access allows the same thing with a little more gymnastics of the form "write stuff to `~/.profile`, or `~/.config/autostart`, or…)

I don't think I'll have time to work on this myself in the near future though, sorry.

**Comment by barthalion** [comment]
I recommend bundling git or switching to Sdk.

**Comment by bbhtt** [comment]
I think adding git to the sandbox is the easiest and safest option that should satisfy most uses-cases. So I did so in the above PR, please test.

(I'm fine with switching to SDK or flatpak-spawn as a solution, although both have some demerits.)

**Comment by albfan** [comment]
Probably people expects to use the git they have on their system. I do 't want to be the blocker of this old/new feature not present

I would go for flatpak-spawn, PR welcome!

**Comment by bbhtt** [comment]
An exception needs to be asked in the flathub/flatpak-builder-lint repository first to make the build succeed.

**Comment by bbhtt** [comment]
https://github.com/flathub/flatpak-builder-lint/pull/147

**Comment by albfan** [comment]
I think then mode to Sdk is the option, right?

**Comment by bbhtt** [comment]
If you only want git then building it here or copying the git executable from the SDK makes most sense I think. If you want git and other CLI tools that are included in the SDK using the SDK is better.

Using the SDK has the downside of the large download and install size, and it's not very common, so users might need it just for this application:

```sh
flatpak list --columns name,ref,size|egrep "org.gnome.Platform/x86_64/44|org.gnome.Sdk/x86_64/44"

GNOME Application Platform version 44	org.gnome.Platform/x86_64/44	860.6 MB
GNOME Software Development Kit version 44	org.gnome.Sdk/x86_64/44	1.9 GB
```

**Comment by hfiguiere** [comment]
Many apps bundle git. FreeCAD, Darktable, come to mind.

**Comment by albfan** [comment]
Many thanks Hub,

Darktable looks updated enough:

```
        {
            "name": "git",
            "cleanup": [
                "/share/gitweb"
            ],
            "make-args": [
                "NO_TCLTK=YesPlease",
                "INSTALL_SYMLINKS=1"
            ],
            "make-install-args": [
                "NO_TCLTK=YesPlease",
                "INSTALL_SYMLINKS=1"
            ],
            "post-install": [
                "find . -type f -name perllocal.pod -delete"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.34.1.tar.xz",
                    "sha256": "3a0755dd1cfab71a24dd96df3498c29cd0acd13b04f3d08bf933e81286db802c"
                }
            ]
        },
```

@wjt or @bbhtt do you want to provide feedbak on this? If that covers your needs we can bundle that

**Comment by bbhtt** [comment]
> @wjt or @bbhtt do you want to provide feedbak on this? If that covers your needs we can bundle that

I did the same thing in the above PR @wjt confirmed it works https://github.com/flathub/org.gnome.gitg/pull/27#issuecomment-1619785967
