### ISSUE TITLE
libgit2 does not link against libssh2

### ISSUE THREAD

**Issue by wshanks** [flathub/org.gnome.gitg#45]
I noticed in the build logs that libgit2 gets built without libssh support even though a libssh2 module is also built. git urls seem not to be accepted in the gitg gui. I was trying to use repo as a template for another flatpak that links against libgit2 and noticed this. I am not a gitg user so I might have missed something.

**Comment by albfan** [comment]
This option was changed on libgit2 1.4.0

https://github.com/libgit2/libgit2/commit/6c00fcb76#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL43

Thanks for reporting, working on it
