### ISSUE TITLE
Impossbible to change width of left bar

### ISSUE THREAD

**Issue by linuxrider** [flathub/org.gnome.gitg#6]
It is impossible to change width of left bar with mouse.
It is working for non-flatpak gitg.

**Comment by albfan** [comment]
Cannot reproduce here, is it possible to upload a screencast?

**Comment by linuxrider** [comment]
Tested now on second computer. Turned out to be related to the red glass mouse cursor theme which did not show the corresponding arrows.
See screencast for native gitg 3.26 and flatpak gitg 3.30.
![gitg flatpak 3 30](https://user-images.githubusercontent.com/5882359/52971980-add69b80-33b9-11e9-9933-d3ee8b890d44.gif)
![gitg native 3 26](https://user-images.githubusercontent.com/5882359/52971982-ae6f3200-33b9-11e9-88d1-fce752147809.gif)

**Comment by albfan** [comment]
Not sure what can be the underneath problem, can you try with any other app so you confirm if this is  related to gitg or flatpak and gtk?

**Comment by linuxrider** [comment]
Tried  builder with same result.
It is somehow linked to the redglass mouse pointer theme.
With DMZ -Black  theme is does not happen.

**Comment by albfan** [comment]
You should report there then
